// <auto-generated />
using System;
using AsistenciaPyme.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistenciaPyme.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AsistenciaPymeDbContext))]
    [Migration("20260819060800_ImplementarNominaDepartamental")]
    partial class ImplementarNominaDepartamental
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Administrador", b =>
                {
                    b.Property<int>("IdAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdministrador"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombres");

                    b.HasKey("IdAdministrador");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("administradores", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asistencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("Corregida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("corregida");

                    b.Property<bool>("EsEntradaTardia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_entrada_tardia");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("FechaCorreccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_correccion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_entrada");

                    b.Property<DateTime?>("HoraProgramadaEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_programada_entrada");

                    b.Property<DateTime?>("HoraProgramadaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_programada_salida");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_salida");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int>("MinutosTardanza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("minutos_tardanza");

                    b.Property<string>("MotivoCorreccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_correccion");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado", "HoraEntrada");

                    b.ToTable("asistencias", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cargo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Funciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("funciones");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Responsabilidades")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsabilidades");

                    b.HasKey("IdCargo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.ConceptoPlanilla", b =>
                {
                    b.Property<int>("IdConceptoPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdConceptoPlanilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConceptoPlanilla"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("Tipo");

                    b.HasKey("IdConceptoPlanilla");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ConceptosPlanilla", (string)null);

                    b.HasData(
                        new
                        {
                            IdConceptoPlanilla = 1,
                            Activo = true,
                            Codigo = "SALARIO_BASE",
                            Nombre = "Salario Base",
                            Tipo = 1
                        },
                        new
                        {
                            IdConceptoPlanilla = 2,
                            Activo = true,
                            Codigo = "HORA_EXTRA",
                            Nombre = "Hora Extra",
                            Tipo = 1
                        },
                        new
                        {
                            IdConceptoPlanilla = 3,
                            Activo = true,
                            Codigo = "INSS",
                            Nombre = "INSS",
                            Tipo = 2
                        },
                        new
                        {
                            IdConceptoPlanilla = 4,
                            Activo = true,
                            Codigo = "EMBARGO",
                            Nombre = "Embargo",
                            Tipo = 2
                        },
                        new
                        {
                            IdConceptoPlanilla = 5,
                            Activo = true,
                            Codigo = "TARDANZA",
                            Nombre = "Tardanza",
                            Tipo = 2
                        },
                        new
                        {
                            IdConceptoPlanilla = 6,
                            Activo = true,
                            Codigo = "BONIFICACION",
                            Nombre = "Bonificación",
                            Tipo = 1
                        },
                        new
                        {
                            IdConceptoPlanilla = 7,
                            Activo = true,
                            Codigo = "OTRA_DEDUCCION",
                            Nombre = "Otra Deducción",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.ConfiguracionNomina", b =>
                {
                    b.Property<int>("IdConfiguracionNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdConfiguracionNomina");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfiguracionNomina"));

                    b.Property<int>("DiasBaseProrrateoVacaciones")
                        .HasColumnType("integer")
                        .HasColumnName("DiasBaseProrrateoVacaciones");

                    b.Property<decimal>("DiasVacacionesPorMes")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("DiasVacacionesPorMes");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MinutosMaximosVerificacionDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosMaximosVerificacionDepartamento");

                    b.Property<int>("MinutosToleranciaEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosToleranciaEntrada");

                    b.Property<decimal>("MultiplicadorHoraExtra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("MultiplicadorHoraExtra");

                    b.Property<int>("PoliticaDescuentoTardanza")
                        .HasColumnType("integer")
                        .HasColumnName("PoliticaDescuentoTardanza");

                    b.Property<decimal?>("TasaINSS")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TasaINSS");

                    b.HasKey("IdConfiguracionNomina");

                    b.ToTable("ConfiguracionesNomina", (string)null);

                    b.HasData(
                        new
                        {
                            IdConfiguracionNomina = 1,
                            DiasBaseProrrateoVacaciones = 30,
                            DiasVacacionesPorMes = 2.5m,
                            FechaCreacion = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinutosMaximosVerificacionDepartamento = 10,
                            MinutosToleranciaEntrada = 10,
                            MultiplicadorHoraExtra = 2.0m,
                            PoliticaDescuentoTardanza = 1
                        });
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DeduccionPlanilla", b =>
                {
                    b.Property<int>("IdDeduccionPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_deduccion_planilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeduccionPlanilla"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdDetallePlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_planilla");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_planilla");

                    b.Property<int>("IdTipoDeduccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_deduccion");

                    b.Property<decimal>("MontoCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_calculado");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_aplicado");

                    b.HasKey("IdDeduccionPlanilla");

                    b.HasIndex("IdDetallePlanilla");

                    b.HasIndex("IdTipoDeduccion");

                    b.HasIndex("IdPlanilla", "IdTipoDeduccion")
                        .IsUnique();

                    b.ToTable("deducciones_planilla", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartamento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DetalleConceptoPlanilla", b =>
                {
                    b.Property<int>("IdDetalleConceptoPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDetalleConceptoPlanilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleConceptoPlanilla"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<int>("IdConceptoPlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("IdConceptoPlanilla");

                    b.Property<int>("IdDetallePlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("IdDetallePlanilla");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Monto");

                    b.HasKey("IdDetalleConceptoPlanilla");

                    b.HasIndex("IdConceptoPlanilla");

                    b.HasIndex("IdDetallePlanilla");

                    b.ToTable("DetallesConceptoPlanilla", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DetallePlanilla", b =>
                {
                    b.Property<int>("IdDetallePlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDetallePlanilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetallePlanilla"));

                    b.Property<int>("CantidadTardanzas")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadTardanzas");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Cargo");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CodigoEmpleado");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Departamento");

                    b.Property<decimal>("DescuentoTardanza")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("DescuentoTardanza");

                    b.Property<int>("DiasLaborados")
                        .HasColumnType("integer")
                        .HasColumnName("DiasLaborados");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleado");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("IdPlanilla");

                    b.Property<decimal?>("IndemnizacionProyectada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("IndemnizacionProyectada");

                    b.Property<int>("MinutosExtrasAprobados")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosExtrasAprobados");

                    b.Property<int>("MinutosExtrasDetectados")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosExtrasDetectados");

                    b.Property<int>("MinutosLaborados")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosLaborados");

                    b.Property<int>("MinutosTardanza")
                        .HasColumnType("integer")
                        .HasColumnName("MinutosTardanza");

                    b.Property<decimal>("MontoHorasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("MontoHorasExtras");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("NombreEmpleado");

                    b.Property<string>("NumeroINSS")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NumeroINSS");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("SalarioBase");

                    b.Property<decimal>("SalarioNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("SalarioNeto");

                    b.Property<decimal>("SaldoVacaciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("SaldoVacaciones");

                    b.Property<decimal>("TotalDeducciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalDeducciones");

                    b.Property<decimal>("TotalIngresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalIngresos");

                    b.Property<decimal>("VacacionesAcumuladasPeriodo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VacacionesAcumuladasPeriodo");

                    b.HasKey("IdDetallePlanilla");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdPlanilla");

                    b.HasIndex("IdPlanilla", "IdEmpleado")
                        .IsUnique();

                    b.ToTable("DetallesPlanilla", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DispositivoMarcaje", b =>
                {
                    b.Property<int>("IdDispositivoMarcaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDispositivoMarcaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispositivoMarcaje"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("IdDepartamento");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Identificador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("Tipo");

                    b.HasKey("IdDispositivoMarcaje");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("DispositivosMarcaje", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Embargo", b =>
                {
                    b.Property<int>("IdEmbargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdEmbargo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmbargo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleado");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Observacion");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("Porcentaje");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Referencia");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("SaldoPendiente");

                    b.Property<int>("TipoCalculo")
                        .HasColumnType("integer")
                        .HasColumnName("TipoCalculo");

                    b.HasKey("IdEmbargo");

                    b.HasIndex("IdEmpleado", "Activo");

                    b.ToTable("Embargos", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_empleado");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_contratacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCargo")
                        .HasColumnType("integer")
                        .HasColumnName("id_cargo");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_departamento");

                    b.Property<int?>("IdHorarioLaboral")
                        .HasColumnType("integer")
                        .HasColumnName("id_horario_laboral");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroINSS")
                        .HasColumnType("text");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salario_base");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdHorarioLaboral");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.HasIndex("NumeroINSS")
                        .IsUnique()
                        .HasFilter("\"NumeroINSS\" IS NOT NULL");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.EmpleadoDepartamentoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleadoDepartamentoHistorial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("IdDepartamento");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleado");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("EmpleadoDepartamentoHistorials", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.HoraExtra", b =>
                {
                    b.Property<int>("IdHoraExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdHoraExtra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHoraExtra"));

                    b.Property<int?>("AprobadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("AprobadoPor");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("Fecha");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaAprobacion");

                    b.Property<int?>("IdAsistencia")
                        .HasColumnType("integer")
                        .HasColumnName("IdAsistencia");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleado");

                    b.Property<int>("MinutosAprobados")
                        .HasColumnType("int")
                        .HasColumnName("MinutosAprobados");

                    b.Property<int>("MinutosDetectados")
                        .HasColumnType("int")
                        .HasColumnName("MinutosDetectados");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Observacion");

                    b.HasKey("IdHoraExtra");

                    b.HasIndex("IdAsistencia");

                    b.HasIndex("IdEmpleado", "Fecha");

                    b.ToTable("HorasExtras", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.HorarioLaboral", b =>
                {
                    b.Property<int>("IdHorarioLaboral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHorarioLaboral"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DiasLaborales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdHorarioLaboral");

                    b.ToTable("HorariosLaborales");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_planilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanilla"));

                    b.Property<int>("CantidadEmpleados")
                        .HasColumnType("integer");

                    b.Property<int?>("CerradoPor")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("FechaFinPeriodo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_periodo");

                    b.Property<DateTime?>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateOnly>("FechaInicioPeriodo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_periodo");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_departamento");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("IngresosAdicionales")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ingresos_adicionales");

                    b.Property<decimal>("SalarioBasePeriodo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salario_base_periodo");

                    b.Property<decimal>("SalarioNeto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("salario_neto");

                    b.Property<decimal>("TotalDeducciones")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_deducciones");

                    b.Property<decimal>("TotalHorasExtras")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_horas_extras");

                    b.Property<decimal>("TotalIngresos")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_ingresos");

                    b.Property<decimal>("TotalNeto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_neto");

                    b.Property<decimal>("TotalSalarioBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_salario_base");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdDepartamento", "FechaInicioPeriodo", "FechaFinPeriodo")
                        .IsUnique();

                    b.ToTable("planillas", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.TipoDeduccion", b =>
                {
                    b.Property<int>("IdTipoDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_deduccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDeduccion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("TipoCalculo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_calculo");

                    b.Property<decimal?>("ValorPredeterminado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_predeterminado");

                    b.HasKey("IdTipoDeduccion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_deduccion", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Vacacion", b =>
                {
                    b.Property<int>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vacacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacacion"));

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.HasKey("IdVacacion");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado", "FechaInicio", "FechaFin");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.VerificacionPresencia", b =>
                {
                    b.Property<int>("IdVerificacionPresencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdVerificacionPresencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVerificacionPresencia"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaHora");

                    b.Property<int?>("IdAsistencia")
                        .HasColumnType("integer")
                        .HasColumnName("IdAsistencia");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("integer")
                        .HasColumnName("IdDepartamento");

                    b.Property<int?>("IdDispositivoMarcaje")
                        .HasColumnType("integer")
                        .HasColumnName("IdDispositivoMarcaje");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpleado");

                    b.HasKey("IdVerificacionPresencia");

                    b.HasIndex("IdAsistencia");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdDispositivoMarcaje");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("VerificacionesPresencia", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "AdministradorCorreccion")
                        .WithMany("AsistenciasCorregidas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdministradorCorreccion");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DeduccionPlanilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.DetallePlanilla", "DetallePlanilla")
                        .WithMany()
                        .HasForeignKey("IdDetallePlanilla")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Planilla", "Planilla")
                        .WithMany("Deducciones")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.TipoDeduccion", "TipoDeduccion")
                        .WithMany("DeduccionesPlanilla")
                        .HasForeignKey("IdTipoDeduccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetallePlanilla");

                    b.Navigation("Planilla");

                    b.Navigation("TipoDeduccion");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DetalleConceptoPlanilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.ConceptoPlanilla", "ConceptoPlanilla")
                        .WithMany("Detalles")
                        .HasForeignKey("IdConceptoPlanilla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.DetallePlanilla", "DetallePlanilla")
                        .WithMany("Conceptos")
                        .HasForeignKey("IdDetallePlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptoPlanilla");

                    b.Navigation("DetallePlanilla");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DetallePlanilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Planilla", "Planilla")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DispositivoMarcaje", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Embargo", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Embargos")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.HorarioLaboral", "HorarioLaboral")
                        .WithMany("Empleados")
                        .HasForeignKey("IdHorarioLaboral")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");

                    b.Navigation("HorarioLaboral");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.EmpleadoDepartamentoHistorial", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("DepartamentoHistorial")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.HoraExtra", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Asistencia", "Asistencia")
                        .WithMany()
                        .HasForeignKey("IdAsistencia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("HorasExtras")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "Administrador")
                        .WithMany("PlanillasGeneradas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Planillas")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Administrador");

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Vacacion", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "Administrador")
                        .WithMany("VacacionesRegistradas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.VerificacionPresencia", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Asistencia", "Asistencia")
                        .WithMany()
                        .HasForeignKey("IdAsistencia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AsistenciaPyme.Domain.Entities.DispositivoMarcaje", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("IdDispositivoMarcaje")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Departamento");

                    b.Navigation("Dispositivo");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("AsistenciasCorregidas");

                    b.Navigation("PlanillasGeneradas");

                    b.Navigation("VacacionesRegistradas");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.ConceptoPlanilla", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DetallePlanilla", b =>
                {
                    b.Navigation("Conceptos");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("DepartamentoHistorial");

                    b.Navigation("Embargos");

                    b.Navigation("HorasExtras");

                    b.Navigation("Planillas");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.HorarioLaboral", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.Navigation("Deducciones");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.TipoDeduccion", b =>
                {
                    b.Navigation("DeduccionesPlanilla");
                });
#pragma warning restore 612, 618
        }
    }
}
