// <auto-generated />
using System;
using AsistenciaPyme.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistenciaPyme.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AsistenciaPymeDbContext))]
    partial class AsistenciaPymeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Administrador", b =>
                {
                    b.Property<int>("IdAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdministrador"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombres");

                    b.HasKey("IdAdministrador");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("administradores", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asistencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("Corregida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("corregida");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("FechaCorreccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_correccion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_entrada");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_salida");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<string>("MotivoCorreccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_correccion");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado", "HoraEntrada");

                    b.ToTable("asistencias", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cargo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Funciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("funciones");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Responsabilidades")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsabilidades");

                    b.HasKey("IdCargo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DeduccionPlanilla", b =>
                {
                    b.Property<int>("IdDeduccionPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_deduccion_planilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeduccionPlanilla"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_planilla");

                    b.Property<int>("IdTipoDeduccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_deduccion");

                    b.Property<decimal>("MontoCalculado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_calculado");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_aplicado");

                    b.HasKey("IdDeduccionPlanilla");

                    b.HasIndex("IdTipoDeduccion");

                    b.HasIndex("IdPlanilla", "IdTipoDeduccion")
                        .IsUnique();

                    b.ToTable("deducciones_planilla", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_empleado");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateOnly>("FechaContratacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_contratacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCargo")
                        .HasColumnType("integer")
                        .HasColumnName("id_cargo");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombres");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_base");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdCargo");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_planilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanilla"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("FechaFinPeriodo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_periodo");

                    b.Property<DateTime?>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateOnly>("FechaInicioPeriodo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_periodo");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("IngresosAdicionales")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ingresos_adicionales");

                    b.Property<decimal>("SalarioBasePeriodo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_base_periodo");

                    b.Property<decimal>("SalarioNeto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("salario_neto");

                    b.Property<decimal>("TotalDeducciones")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_deducciones");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado", "FechaInicioPeriodo", "FechaFinPeriodo")
                        .IsUnique();

                    b.ToTable("planillas", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.TipoDeduccion", b =>
                {
                    b.Property<int>("IdTipoDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_deduccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDeduccion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("TipoCalculo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_calculo");

                    b.Property<decimal?>("ValorPredeterminado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_predeterminado");

                    b.HasKey("IdTipoDeduccion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_deduccion", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Vacacion", b =>
                {
                    b.Property<int>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vacacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacacion"));

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.HasKey("IdVacacion");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEmpleado", "FechaInicio", "FechaFin");

                    b.ToTable("vacaciones", (string)null);
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "AdministradorCorreccion")
                        .WithMany("AsistenciasCorregidas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdministradorCorreccion");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.DeduccionPlanilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Planilla", "Planilla")
                        .WithMany("Deducciones")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.TipoDeduccion", "TipoDeduccion")
                        .WithMany("DeduccionesPlanilla")
                        .HasForeignKey("IdTipoDeduccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planilla");

                    b.Navigation("TipoDeduccion");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "Administrador")
                        .WithMany("PlanillasGeneradas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Vacacion", b =>
                {
                    b.HasOne("AsistenciaPyme.Domain.Entities.Administrador", "Administrador")
                        .WithMany("VacacionesRegistradas")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistenciaPyme.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("AsistenciasCorregidas");

                    b.Navigation("PlanillasGeneradas");

                    b.Navigation("VacacionesRegistradas");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Planillas");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.Planilla", b =>
                {
                    b.Navigation("Deducciones");
                });

            modelBuilder.Entity("AsistenciaPyme.Domain.Entities.TipoDeduccion", b =>
                {
                    b.Navigation("DeduccionesPlanilla");
                });
#pragma warning restore 612, 618
        }
    }
}
